SET NAMES utf8mb4;
UPDATE sys_user SET real_name=CONVERT(UNHEX('E99988E699A8') USING utf8mb4) WHERE username LIKE 'DEMO_U_%' AND MOD(CAST(SUBSTRING_INDEX(username, '_', -1) AS UNSIGNED), 10)=0;
UPDATE sys_user SET real_name=CONVERT(UNHEX('E69E97E5B29A') USING utf8mb4) WHERE username LIKE 'DEMO_U_%' AND MOD(CAST(SUBSTRING_INDEX(username, '_', -1) AS UNSIGNED), 10)=1;
UPDATE sys_user SET real_name=CONVERT(UNHEX('E9BB84E6B5B7') USING utf8mb4) WHERE username LIKE 'DEMO_U_%' AND MOD(CAST(SUBSTRING_INDEX(username, '_', -1) AS UNSIGNED), 10)=2;
UPDATE sys_user SET real_name=CONVERT(UNHEX('E590B4E6A190') USING utf8mb4) WHERE username LIKE 'DEMO_U_%' AND MOD(CAST(SUBSTRING_INDEX(username, '_', -1) AS UNSIGNED), 10)=3;
UPDATE sys_user SET real_name=CONVERT(UNHEX('E5BE90E682A6') USING utf8mb4) WHERE username LIKE 'DEMO_U_%' AND MOD(CAST(SUBSTRING_INDEX(username, '_', -1) AS UNSIGNED), 10)=4;
UPDATE sys_user SET real_name=CONVERT(UNHEX('E4BD95E5AE81') USING utf8mb4) WHERE username LIKE 'DEMO_U_%' AND MOD(CAST(SUBSTRING_INDEX(username, '_', -1) AS UNSIGNED), 10)=5;
UPDATE sys_user SET real_name=CONVERT(UNHEX('E7BD97E998B3') USING utf8mb4) WHERE username LIKE 'DEMO_U_%' AND MOD(CAST(SUBSTRING_INDEX(username, '_', -1) AS UNSIGNED), 10)=6;
UPDATE sys_user SET real_name=CONVERT(UNHEX('E9AB98E7BF94') USING utf8mb4) WHERE username LIKE 'DEMO_U_%' AND MOD(CAST(SUBSTRING_INDEX(username, '_', -1) AS UNSIGNED), 10)=7;
UPDATE sys_user SET real_name=CONVERT(UNHEX('E6A281E99D99') USING utf8mb4) WHERE username LIKE 'DEMO_U_%' AND MOD(CAST(SUBSTRING_INDEX(username, '_', -1) AS UNSIGNED), 10)=8;
UPDATE sys_user SET real_name=CONVERT(UNHEX('E5AE8BE5AE87') USING utf8mb4) WHERE username LIKE 'DEMO_U_%' AND MOD(CAST(SUBSTRING_INDEX(username, '_', -1) AS UNSIGNED), 10)=9;
UPDATE sys_user u JOIN area a ON a.id=u.area_id SET u.address=CONCAT(CONVERT(UNHEX('E7A4BAE88C83E58CBA41') USING utf8mb4), SUBSTRING_INDEX(u.username, '_', -1), CONVERT(UNHEX('E58FB7E6A5BC') USING utf8mb4)) WHERE a.area_code='A001' AND u.username LIKE 'DEMO_U_%';
UPDATE water_meter m JOIN area a ON a.id=m.area_id SET m.install_address=CONCAT(CONVERT(UNHEX('E7A4BAE88C83E58CBA41') USING utf8mb4), ' ', m.meter_no) WHERE a.area_code='A001' AND m.remark='DEMO_SHOW';
UPDATE sys_user u JOIN area a ON a.id=u.area_id SET u.address=CONCAT(CONVERT(UNHEX('E7A4BAE88C83E58CBA42') USING utf8mb4), SUBSTRING_INDEX(u.username, '_', -1), CONVERT(UNHEX('E58FB7E6A5BC') USING utf8mb4)) WHERE a.area_code='B001' AND u.username LIKE 'DEMO_U_%';
UPDATE water_meter m JOIN area a ON a.id=m.area_id SET m.install_address=CONCAT(CONVERT(UNHEX('E7A4BAE88C83E58CBA42') USING utf8mb4), ' ', m.meter_no) WHERE a.area_code='B001' AND m.remark='DEMO_SHOW';
UPDATE sys_user u JOIN area a ON a.id=u.area_id SET u.address=CONCAT(CONVERT(UNHEX('E7A4BAE88C83E58CBA43') USING utf8mb4), SUBSTRING_INDEX(u.username, '_', -1), CONVERT(UNHEX('E58FB7E6A5BC') USING utf8mb4)) WHERE a.area_code='C001' AND u.username LIKE 'DEMO_U_%';
UPDATE water_meter m JOIN area a ON a.id=m.area_id SET m.install_address=CONCAT(CONVERT(UNHEX('E7A4BAE88C83E58CBA43') USING utf8mb4), ' ', m.meter_no) WHERE a.area_code='C001' AND m.remark='DEMO_SHOW';
UPDATE sys_user u JOIN area a ON a.id=u.area_id SET u.address=CONCAT(CONVERT(UNHEX('E7A4BAE88C83E58CBA44') USING utf8mb4), SUBSTRING_INDEX(u.username, '_', -1), CONVERT(UNHEX('E58FB7E6A5BC') USING utf8mb4)) WHERE a.area_code='D001' AND u.username LIKE 'DEMO_U_%';
UPDATE water_meter m JOIN area a ON a.id=m.area_id SET m.install_address=CONCAT(CONVERT(UNHEX('E7A4BAE88C83E58CBA44') USING utf8mb4), ' ', m.meter_no) WHERE a.area_code='D001' AND m.remark='DEMO_SHOW';
SELECT username, real_name, HEX(real_name) FROM sys_user WHERE username LIKE 'DEMO_U_A001_%%' LIMIT 3;