SET NAMES utf8mb4;
CREATE TABLE IF NOT EXISTS automation_coverage_policy (
 id TINYINT PRIMARY KEY, enabled BOOLEAN NOT NULL DEFAULT FALSE,
 interval_minutes INT NOT NULL DEFAULT 1440,
 increment_amount DECIMAL(12,2) NOT NULL DEFAULT 1.00,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT IGNORE INTO automation_coverage_policy(id) VALUES(1);
CREATE TABLE IF NOT EXISTS automation_coverage_meter (
 meter_id BIGINT PRIMARY KEY, plan_id BIGINT NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY uk_coverage_plan(plan_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
