package com.water.ai.meter.diagnosis;
import com.water.ai.meter.security.SessionUser;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.jdbc.core.JdbcTemplate;
import java.time.*;
import java.util.*;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.*;

@EnabledIfEnvironmentVariable(named="BILLING_MYSQL_TESTS",matches="true")
@SpringBootTest(properties={"spring.datasource.url=jdbc:mysql://localhost:3308/water_meter_billing_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true","spring.datasource.username=root","spring.datasource.password=123456","spring.main.web-application-type=none","spring.cloud.nacos.discovery.enabled=false","automation.scheduling.enabled=false","diagnosis.scheduling.enabled=false","logging.level.root=WARN","logging.level.com.water.ai.meter=WARN","logging.file.name=../logs/innovation-tests.log","mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.nologging.NoLoggingImpl"})
class DiagnosticProbeMySqlIntegrationTest {
 @Autowired JdbcTemplate jdbc;@org.springframework.boot.test.mock.mockito.SpyBean ObservationService observations;@Autowired DiagnosisService diagnosis;@Autowired DiagnosticProbeService probes;
 @MockBean DiagnosisClient client;long user,meter;String key;Map<String,Object> saved;SessionUser admin;
 @Autowired com.water.ai.meter.notification.NotificationService notifications;
 @Autowired org.springframework.transaction.PlatformTransactionManager manager;
 @BeforeEach void setup(){assertThat(jdbc.queryForObject("SELECT DATABASE()",String.class)).isEqualTo("water_meter_billing_test");saved=diagnosis.policy();key="PROBE_"+UUID.randomUUID().toString().replace("-","");
  jdbc.update("INSERT INTO sys_user(username,password) VALUES(?,'test')",key);user=jdbc.queryForObject("SELECT id FROM sys_user WHERE username=?",Long.class,key);admin=new SessionUser(user,key,"测试","admin");
  jdbc.update("INSERT INTO water_meter(meter_no,user_id,current_reading) VALUES(?,?,100)",key,user);meter=jdbc.queryForObject("SELECT id FROM water_meter WHERE meter_no=?",Long.class,key);
  when(client.score(eq(meter),anyList())).thenReturn(Map.of("decision","needs_review","reasonCodes",List.of("persistent_flow_above_personal_baseline"),"baseline",Map.of("median",.02,"upper",.07,"ready",true),"features",Map.of("intervalFlow",.12),"modelVersion","test-baseline"));
 }
 @AfterEach void cleanup(){
  jdbc.update("DELETE FROM diagnosis_action WHERE actor_id=?",user);jdbc.update("DELETE p FROM diagnostic_probe p JOIN diagnosis_case c ON c.id=p.case_id WHERE c.meter_id=?",meter);
  jdbc.update("DELETE FROM notification_read WHERE user_id=?",user);
  jdbc.update("DELETE e FROM diagnosis_evidence e JOIN diagnosis_case c ON c.id=e.case_id WHERE c.meter_id=?",meter);jdbc.update("DELETE FROM diagnosis_case_guard WHERE meter_id=?",meter);jdbc.update("DELETE FROM diagnosis_case WHERE meter_id=?",meter);
  jdbc.update("DELETE j FROM diagnosis_job j JOIN meter_observation o ON o.id=j.observation_id WHERE o.meter_id=?",meter);jdbc.update("DELETE FROM observation_attempt WHERE meter_id=?",meter);jdbc.update("DELETE FROM observation_cursor WHERE meter_id=?",meter);jdbc.update("DELETE FROM meter_observation WHERE meter_id=?",meter);
  jdbc.update("DELETE FROM diagnostic_budget WHERE meter_id=?",meter);jdbc.update("DELETE FROM anomaly_record WHERE meter_id=?",meter);jdbc.update("DELETE FROM diagnosis_policy_audit WHERE actor_id=?",user);
  jdbc.update("DELETE FROM water_meter WHERE id=?",meter);jdbc.update("DELETE FROM sys_user WHERE id=?",user);jdbc.update("UPDATE diagnosis_policy SET version=?,mode=?,meter_ids=? WHERE id=1",saved.get("version"),saved.get("mode"),DiagnosisSupport.json(saved.get("meterIds")));
 }
 long candidate(String mode){diagnosis.savePolicy(new DiagnosisService.Policy(((Number)diagnosis.policy().get("version")).longValue(),mode,List.of(meter)),user);
  observations.ingest(key+"|"+LocalDateTime.now(ZoneId.of("Asia/Shanghai")).minusHours(1).withNano(0)+"|0.12|101|25|OPEN|0",key,user);diagnosis.tick();return jdbc.queryForObject("SELECT id FROM diagnosis_case WHERE meter_id=?",Long.class,meter);}
 @Test void shadowOnlyRecordsEvidenceWithoutOfficialAlertsOrProbes(){long id=candidate("shadow");assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM diagnostic_probe WHERE case_id=?",Long.class,id)).isZero();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM anomaly_record WHERE meter_id=?",Long.class,meter)).isZero();assertThat(diagnosis.cases(1,20,null,null,user).get("total")).isEqualTo(0L);}
 @Test void repeatedRequestsNeverCreateAnotherSetOfThreeProbes(){long id=candidate("assisted");for(int i=0;i<5;i++)diagnosis.action(id,"probe",Map.of("requestKey",key+i),admin);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM diagnostic_probe WHERE case_id=?",Long.class,id)).isEqualTo(3);}
 @Test void budgetExhaustionNeverReportsNormalAndLeavesFinanceUntouched(){long id=candidate("assisted");jdbc.update("INSERT INTO diagnostic_budget VALUES(?,?,24)",meter,LocalDate.now(ZoneId.of("Asia/Shanghai")));jdbc.update("UPDATE diagnostic_probe SET due_at=DATE_SUB(NOW(),INTERVAL 1 SECOND) WHERE case_id=?",id);probes.tick();assertThat(jdbc.queryForObject("SELECT state FROM diagnosis_case WHERE id=?",String.class,id)).isEqualTo("needs_review");assertThat(jdbc.queryForObject("SELECT SUM(attempts) FROM diagnostic_probe WHERE case_id=?",Long.class,id)).isZero();assertThat(jdbc.queryForObject("SELECT current_reading FROM water_meter WHERE id=?",java.math.BigDecimal.class,meter)).isEqualByComparingTo("100");}
 @Test void disablingCancelsPendingButDoesNotTouchOrdinaryPlans(){long id=candidate("assisted");long planCount=jdbc.queryForObject("SELECT COUNT(*) FROM automation_plan WHERE enabled=1",Long.class);diagnosis.savePolicy(new DiagnosisService.Policy(((Number)diagnosis.policy().get("version")).longValue(),"off",List.of()),user);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM diagnostic_probe WHERE case_id=? AND state='cancelled'",Long.class,id)).isEqualTo(3);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM automation_plan WHERE enabled=1",Long.class)).isEqualTo(planCount);}
 @Test void firstSimulationProbeIsFreshAndDoesNotBill(){long id=candidate("assisted");long p=jdbc.queryForObject("SELECT MIN(id) FROM diagnostic_probe WHERE case_id=?",Long.class,id);jdbc.update("UPDATE diagnostic_probe SET due_at=DATE_SUB(NOW(),INTERVAL 1 SECOND) WHERE id=?",p);probes.process(p);assertThat(jdbc.queryForObject("SELECT state FROM diagnostic_probe WHERE id=?",String.class,p)).isEqualTo("success");assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM meter_observation WHERE meter_id=?",Long.class,meter)).isEqualTo(2);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM bill WHERE user_id=?",Long.class,user)).isZero();}
 @Test void stoppedMeterCancelsWithoutRequest(){long id=candidate("assisted");jdbc.update("UPDATE water_meter SET status=2 WHERE id=?",meter);jdbc.update("UPDATE diagnostic_probe SET due_at=DATE_SUB(NOW(),INTERVAL 1 SECOND) WHERE case_id=?",id);probes.tick();assertThat(jdbc.queryForObject("SELECT SUM(attempts) FROM diagnostic_probe WHERE case_id=?",Long.class,id)).isZero();}
 @Test void shadowCannotBeReadThroughOwnedDetail(){long id=candidate("shadow");assertThatThrownBy(()->diagnosis.detail(id,user)).isInstanceOf(org.springframework.web.server.ResponseStatusException.class);}
 @Test void distinctConcurrentProbesCannotClaimTheSameObservation() throws Exception {
  long id=candidate("assisted");var fixed=new DiagnosticProbeService(jdbc,Clock.fixed(Instant.now().minusSeconds(1),ZoneId.of("Asia/Shanghai")),manager,observations);
  var ids=jdbc.queryForList("SELECT id FROM diagnostic_probe WHERE case_id=? ORDER BY id LIMIT 2",Long.class,id);jdbc.update("UPDATE diagnostic_probe SET due_at=DATE_SUB(NOW(),INTERVAL 1 MINUTE) WHERE case_id=?",id);
  var received=new java.util.concurrent.CountDownLatch(2);
  doAnswer(inv->{var result=inv.callRealMethod();received.countDown();assertThat(received.await(10,java.util.concurrent.TimeUnit.SECONDS)).isTrue();return result;}).when(observations).ingest(anyString(),startsWith("probe:"),anyLong());
  var pool=java.util.concurrent.Executors.newFixedThreadPool(2);try{var a=pool.submit(()->fixed.process(ids.get(0)));var b=pool.submit(()->fixed.process(ids.get(1)));a.get(20,java.util.concurrent.TimeUnit.SECONDS);b.get(20,java.util.concurrent.TimeUnit.SECONDS);}finally{pool.shutdownNow();}
  assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM diagnostic_probe WHERE case_id=? AND state='success'",Integer.class,id)).isEqualTo(1);
  assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM diagnostic_probe WHERE case_id=? AND state='retry'",Integer.class,id)).isEqualTo(1);
 }
 @Test void cancellationAndAdmissionCompleteWithoutDeadlock() throws Exception {long id=candidate("assisted");long p=jdbc.queryForObject("SELECT MIN(id) FROM diagnostic_probe WHERE case_id=?",Long.class,id);jdbc.update("UPDATE diagnostic_probe SET due_at=DATE_SUB(NOW(),INTERVAL 1 MINUTE) WHERE id=?",p);var pool=java.util.concurrent.Executors.newFixedThreadPool(2);var gate=new java.util.concurrent.CountDownLatch(1);try{var a=pool.submit(()->{gate.await();probes.process(p);return true;});var b=pool.submit(()->{gate.await();diagnosis.action(id,"cancel-probes",Map.of("requestKey",key+"cancel","reason","停止本轮"),admin);return true;});gate.countDown();a.get(20,java.util.concurrent.TimeUnit.SECONDS);b.get(20,java.util.concurrent.TimeUnit.SECONDS);}finally{pool.shutdownNow();}assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM diagnostic_probe WHERE case_id=? AND state IN ('pending','retry')",Integer.class,id)).isZero();}
 @Test void repeatedDeviceInstantCannotBecomeThreeSuccessfulProbes(){long id=candidate("assisted");var now=Instant.now().minusSeconds(1);var fixed=new DiagnosticProbeService(jdbc,Clock.fixed(now,ZoneId.of("Asia/Shanghai")),manager,observations);for(int attempt=0;attempt<2;attempt++){jdbc.update("UPDATE diagnostic_probe SET due_at=DATE_SUB(NOW(),INTERVAL 1 MINUTE) WHERE case_id=? AND state IN ('pending','retry')",id);fixed.tick();}assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM diagnostic_probe WHERE case_id=? AND state='success'",Integer.class,id)).isEqualTo(1);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM meter_observation WHERE meter_id=?",Integer.class,meter)).isEqualTo(2);assertThat(jdbc.queryForObject("SELECT state FROM diagnosis_case WHERE id=?",String.class,id)).isEqualTo("needs_review");}
 @Test void twoWorkersClaimSameProbeOnce() throws Exception {long id=candidate("assisted");long p=jdbc.queryForObject("SELECT MIN(id) FROM diagnostic_probe WHERE case_id=?",Long.class,id);jdbc.update("UPDATE diagnostic_probe SET due_at=DATE_SUB(NOW(),INTERVAL 1 MINUTE) WHERE id=?",p);var pool=java.util.concurrent.Executors.newFixedThreadPool(2);try{var gate=new java.util.concurrent.CountDownLatch(1);var a=pool.submit(()->{gate.await();probes.process(p);return true;});var b=pool.submit(()->{gate.await();probes.process(p);return true;});gate.countDown();a.get(20,java.util.concurrent.TimeUnit.SECONDS);b.get(20,java.util.concurrent.TimeUnit.SECONDS);}finally{pool.shutdownNow();}assertThat(jdbc.queryForObject("SELECT requests FROM diagnostic_budget WHERE meter_id=?",Integer.class,meter)).isEqualTo(1);assertThat(jdbc.queryForObject("SELECT attempts FROM diagnostic_probe WHERE id=?",Integer.class,p)).isEqualTo(1);}
 @Test void allFailuresStopAtSixRequestsAndNeverRecover(){long id=candidate("assisted");jdbc.update("UPDATE meter_observation SET source='unconfigured' WHERE meter_id=?",meter);for(int i=0;i<2;i++){jdbc.update("UPDATE diagnostic_probe SET due_at=DATE_SUB(NOW(),INTERVAL 1 MINUTE) WHERE case_id=?",id);probes.tick();}assertThat(jdbc.queryForObject("SELECT SUM(attempts) FROM diagnostic_probe WHERE case_id=?",Integer.class,id)).isEqualTo(6);assertThat(jdbc.queryForObject("SELECT requests FROM diagnostic_budget WHERE meter_id=?",Integer.class,meter)).isEqualTo(6);assertThat(jdbc.queryForObject("SELECT state FROM diagnosis_case WHERE id=?",String.class,id)).isEqualTo("needs_review");}
 @Test void expiredAnalysisLeaseDoesNotDuplicateCaseOrEvidence(){long id=candidate("assisted");jdbc.update("UPDATE diagnosis_job j JOIN meter_observation o ON o.id=j.observation_id SET j.state='running',j.lease_until=DATE_SUB(NOW(),INTERVAL 1 MINUTE),j.next_at=DATE_SUB(NOW(),INTERVAL 1 MINUTE) WHERE o.meter_id=?",meter);diagnosis.tick();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM diagnosis_case WHERE meter_id=?",Long.class,meter)).isEqualTo(1);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM diagnosis_evidence WHERE case_id=?",Long.class,id)).isEqualTo(1);}
 @Test void expiredLeaseRecoversOnceAndChargesRetryBudget(){long id=candidate("assisted");long p=jdbc.queryForObject("SELECT MIN(id) FROM diagnostic_probe WHERE case_id=?",Long.class,id);jdbc.update("UPDATE diagnostic_probe SET state='running',attempts=1,lease_token='old-worker',lease_until=DATE_SUB(NOW(),INTERVAL 1 MINUTE),due_at=DATE_SUB(NOW(),INTERVAL 1 MINUTE) WHERE id=?",p);jdbc.update("INSERT INTO diagnostic_budget VALUES(?,?,1)",meter,LocalDate.now(ZoneId.of("Asia/Shanghai")));probes.process(p);probes.process(p);assertThat(jdbc.queryForObject("SELECT attempts FROM diagnostic_probe WHERE id=?",Integer.class,p)).isEqualTo(2);assertThat(jdbc.queryForObject("SELECT state FROM diagnostic_probe WHERE id=?",String.class,p)).isEqualTo("success");assertThat(jdbc.queryForObject("SELECT requests FROM diagnostic_budget WHERE meter_id=?",Integer.class,meter)).isEqualTo(2);}
 @Test void modelFailureRetriesWithBasicRulesWithoutBilling(){when(client.score(eq(meter),anyList())).thenThrow(new IllegalStateException("offline"));when(client.fallback(anyMap())).thenReturn(Map.of("decision","insufficient_data","reasonCodes",List.of("cold_start"),"features",Map.of(),"baseline",Map.of(),"modelVersion","rules-only"));diagnosis.savePolicy(new DiagnosisService.Policy(((Number)diagnosis.policy().get("version")).longValue(),"assisted",List.of(meter)),user);observations.ingest(key+"|"+LocalDateTime.now(ZoneId.of("Asia/Shanghai")).minusHours(1).withNano(0)+"|0.12|101|25|OPEN|0",key,user);diagnosis.tick();assertThat(jdbc.queryForObject("SELECT state FROM diagnosis_job j JOIN meter_observation o ON o.id=j.observation_id WHERE o.meter_id=?",String.class,meter)).isEqualTo("retry");assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM bill WHERE user_id=?",Long.class,user)).isZero();}
 @Test void notificationChangesOnlyWhenStateChanges(){long id=candidate("assisted");var me=new SessionUser(user,key,"测试","user");var first=notifications.inbox(me).items().stream().filter(m->m.category().equals("diagnosis")&&m.sourceId()==id).findFirst().orElseThrow();notifications.mark(me,List.of(first.key()),true);jdbc.update("UPDATE diagnosis_case SET last_evidence_at=DATE_ADD(last_evidence_at,INTERVAL 1 MINUTE) WHERE id=?",id);assertThat(notifications.inbox(me).items()).anyMatch(m->m.key().equals(first.key())&&m.read());jdbc.update("UPDATE diagnosis_case SET state='needs_review' WHERE id=?",id);assertThat(notifications.inbox(me).items()).anyMatch(m->m.category().equals("diagnosis")&&m.sourceId()==id&&!m.key().equals(first.key())&&!m.read());}
 @Test void newPolicyDoesNotMixEvidenceIntoShadowCase(){long old=candidate("shadow");diagnosis.savePolicy(new DiagnosisService.Policy(((Number)diagnosis.policy().get("version")).longValue(),"assisted",List.of(meter)),user);observations.ingest(key+"|"+LocalDateTime.now(ZoneId.of("Asia/Shanghai")).minusMinutes(30).withNano(0)+"|0.12|102|25|OPEN|0",key+"new",user);diagnosis.tick();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM diagnosis_case WHERE meter_id=?",Long.class,meter)).isEqualTo(2);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM diagnosis_evidence WHERE case_id=?",Long.class,old)).isEqualTo(1);assertThat(diagnosis.cases(1,20,null,null,user).get("total")).isEqualTo(1L);}
}
